### ISSUE TITLE
 object 'altitude' not found when using souding_wind.

### ISSUE THREAD

**Issue by NMC-DAVE** [bczernecki/thundeR#23]
Hi,
     When I use `souding_wind` with my own data, I got the error:

 `object 'altitude' not found`

I think the sounding_wind function misses the altitude parameter. So, please fix it. Thanks very much.

**Comment by bczernecki** [comment]
@NMC-DAVE - thanks for discovering the bug! The commit that solves it has been now pushed to our 'devel' branch. It will be available on CRAN in the next release that is planned in the first part of April.
