### ISSUE TITLE
Thunder does not run in latest R.

### ISSUE THREAD

**Issue by GeorgeMJ23** [bczernecki/thundeR#29]
I'm using R version 4.05 and when i'm trying to install Thunder via **install.packages("thunder")** it says:

Warning message:
package ‘thunder’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,

So i cannot install it.
Any ideas?

**Comment by bczernecki** [comment]
Hi @GeorgeMJ23 ,

First of all - thank you for the feedback! We do apprecciate it!
You're absolutely right, there's no thunder in the CRAN repository. Currently we are pending some minor updates and by the time it is not validated it won't be available on CRAN.

However, you can still install it directly from our Github repo:

```
install.packages("remotes")
remotes::install_github("bczernecki/thunder")
```

Hope that helps :)
