### ISSUE TITLE
Quality control

### ISSUE THREAD

**Issue by nuerdadahachi** [bczernecki/thundeR#36]
There is a question. Not see the 'thunder' source code, so I don't know if 'thunder' includes quality control of sounding measurements. Obviously, 'thunder' has excluded levels with incomplete measurements (e.g., temperature was available but dewpoints were missing). I know from "Climatological Aspects of Convective Parameters over Europe: A Comparison of ERA-Interim and Sounding Data" that quality control is a must. Then, did 'thunder' discards radiosonde measurements with obvious or unrealistic errors?

**Comment by bczernecki** [comment]
`thundeR` doesn't provide currently any method to filter out suspicious soundings. Therefore pre-processing/cleaning should be done on a user level, similarly as it is done in other software for sounding processing.
