### ISSUE TITLE
package ‘thunder’ is not available (for R version 3.6.0)

### ISSUE THREAD

**Issue by fermidq** [bczernecki/thundeR#37]
Hi：
    When I install the package "thunder" on Windows10, it is shown that "package ‘thunder’ is not available (for R version 3.6.0)".
    When I install the 'thunder' on R version 4.1.2 on Windows10, it is not available too.
   I tried on centos7.6 with R version 3.6.0 and the errors are same.
   On the website of thunder, I cann't find some information for the available R version.
   So which R version should I install the "thunder" on?

**Comment by abigmo** [comment]
Just download master.zip, unzip it and install it directly by
```devtools::install("path to the unzipped forlder/thundeR-master")```

BTW: congratulations to the developers of ThundeR, there was really need of this package.

**Comment by bczernecki** [comment]
Thanks for the feedback @abigmo !
Yes, if you download `master.zip` file using github's web interface it is usually named with the branch name (e.g. `thundeR-master`), so if you want to install it using locally downloaded file then the above mentioned command should work. 

As general rule I think it is simpler to use: 

```
remotes::install_github("bczernecki/thunder")
```
or 
```
devtools::install_github("bczernecki/thunder")
```

which downloads the package using R (i.e. no need to use web browser).
